# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "Yuto's Note"
weight = 1

[zh-tw]
languageName = "Traditional Chinese"
languagedirection = "ltr"
title = "Yuto's Note"
weight = 1
