# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "Yuto's Note"
weight = 2

[zh-tw]
languageName = "繁體中文"
languagedirection = "ltr"
title = "Yuto's Note"
weight = 0

[ja]
languageName = "日本語"
languagedirection = "ltr"
title = "Yuto's Note"
weight = 1
